# Generated by Django 3.2 on 2021-09-29 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("helusers", "0002_add_oidcbackchannellogoutevent"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="customuser",
            name="ad_groups",
            field=models.ManyToManyField(blank=True, to="helusers.ADGroup"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
    ]
