# Generated by Django 3.2 on 2021-09-29 07:33
from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    CustomUser = apps.get_model("users_app", "CustomUser")
    for user in CustomUser.objects.all():
        user.uuid = uuid.uuid4()
        user.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0002_switch_to_django_helusers"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
