# Generated by Django 3.2 on 2021-09-29 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0003_populate_custom_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
