# Generated by Django 3.2 on 2021-12-03 11:28

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parking_permits.models.parking_permit
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True,
                        choices=[("HELSINKI_PROFILE", "Helsinki Profile")],
                        max_length=50,
                        verbose_name="Source system",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Source id"
                    ),
                ),
                (
                    "street_name",
                    models.CharField(max_length=128, verbose_name="Street name"),
                ),
                (
                    "street_name_sv",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Street name sv"
                    ),
                ),
                (
                    "street_number",
                    models.CharField(max_length=128, verbose_name="Street number"),
                ),
                ("city", models.CharField(max_length=128, verbose_name="City")),
                (
                    "city_sv",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="City sv"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Postal code"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Location (2D)"
                    ),
                ),
                (
                    "primary",
                    models.BooleanField(default=False, verbose_name="Primary address"),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True,
                        choices=[("HELSINKI_PROFILE", "Helsinki Profile")],
                        max_length=50,
                        verbose_name="Source system",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Source id"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Last name"
                    ),
                ),
                (
                    "national_id_number",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        unique=True,
                        verbose_name="National identification number",
                    ),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=128, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Phone number"
                    ),
                ),
                (
                    "address_security_ban",
                    models.BooleanField(
                        default=False, verbose_name="Address security ban"
                    ),
                ),
                (
                    "driver_license_checked",
                    models.BooleanField(
                        default=False, verbose_name="Driver's license checked"
                    ),
                ),
                (
                    "other_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers_other_address",
                        to="parking_permits.address",
                        verbose_name="Other address",
                    ),
                ),
                (
                    "primary_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers_primary_address",
                        to="parking_permits.address",
                        verbose_name="Primary address",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="DrivingClass",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "class_name",
                    models.CharField(max_length=32, verbose_name="Driving class name"),
                ),
                (
                    "identifier",
                    models.CharField(
                        max_length=32, verbose_name="Driving class identifier"
                    ),
                ),
            ],
            options={
                "verbose_name": "Driving class",
                "verbose_name_plural": "Driving classes",
            },
        ),
        migrations.CreateModel(
            name="LowEmissionCriteria",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "power_type",
                    models.CharField(
                        choices=[
                            ("BENSIN", "Bensin"),
                            ("DIESEL", "Diesel"),
                            ("BIFUEL", "Bibuel"),
                        ],
                        max_length=50,
                        verbose_name="Power type",
                    ),
                ),
                (
                    "nedc_max_emission_limit",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="NEDC maximum emission limit",
                    ),
                ),
                (
                    "wltp_max_emission_limit",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="WLTP maximum emission limit",
                    ),
                ),
                (
                    "euro_min_class_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Euro minimum class limit"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
            ],
            options={
                "verbose_name": "Low-emission criteria",
                "verbose_name_plural": "Low-emission criterias",
            },
        ),
        migrations.CreateModel(
            name="ParkingPermit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ARRIVED", "Arrived"),
                            ("PROCESSING", "Processing"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("PAYMENT_IN_PROGRESS", "Payment in progress"),
                            ("VALID", "Valid"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "identifier",
                    models.IntegerField(
                        db_index=True,
                        default=parking_permits.models.parking_permit.get_next_identifier,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End time"
                    ),
                ),
                ("primary_vehicle", models.BooleanField(default=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("FIXED_PERIOD", "Fixed period"),
                            ("OPEN_ENDED", "Open ended"),
                        ],
                        default="OPEN_ENDED",
                        max_length=16,
                        verbose_name="Contract type",
                    ),
                ),
                (
                    "start_type",
                    models.CharField(
                        choices=[("IMMEDIATELY", "Immediately"), ("FROM", "From")],
                        default="IMMEDIATELY",
                        max_length=16,
                        verbose_name="Start type",
                    ),
                ),
                (
                    "month_count",
                    models.IntegerField(default=1, verbose_name="Month count"),
                ),
                ("order_id", models.CharField(blank=True, max_length=50)),
                ("subscription_id", models.CharField(blank=True, max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parking_permits.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parking permit",
                "verbose_name_plural": "Parking permits",
                "ordering": ["-identifier"],
            },
        ),
        migrations.CreateModel(
            name="ParkingZone",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_sv",
                    models.TextField(blank=True, verbose_name="Description sv"),
                ),
                (
                    "shared_product_id",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Area (2D)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parking zone",
                "verbose_name_plural": "Parking zones",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "power_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BENSIN", "Bensin"),
                            ("DIESEL", "Diesel"),
                            ("BIFUEL", "Bibuel"),
                        ],
                        max_length=50,
                        verbose_name="Power type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M1", "M1"),
                            ("M2", "M2"),
                            ("N1", "N1"),
                            ("N2", "N2"),
                            ("L3e", "L3E"),
                            ("L4e", "L4E"),
                            ("L5e", "L5E"),
                            ("L6e", "L6E"),
                        ],
                        max_length=16,
                        verbose_name="Category",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="Manufacturer"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                (
                    "production_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Production year"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=24, unique=True, verbose_name="Registration number"
                    ),
                ),
                (
                    "euro_class",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Euro class"
                    ),
                ),
                (
                    "emission",
                    models.IntegerField(blank=True, null=True, verbose_name="Emission"),
                ),
                (
                    "low_emission_vehicle",
                    models.BooleanField(
                        default=False, verbose_name="Low emission vehicle"
                    ),
                ),
                ("consent_low_emission_accepted", models.BooleanField(default=False)),
                (
                    "emission_type",
                    models.CharField(
                        choices=[("EURO", "Euro"), ("NEDC", "Nedc"), ("WLTP", "Wltp")],
                        default="EURO",
                        max_length=16,
                        verbose_name="Emission type",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Serial number"
                    ),
                ),
                (
                    "last_inspection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last inspection date"
                    ),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles_holder",
                        to="parking_permits.customer",
                        verbose_name="Holder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles_owner",
                        to="parking_permits.customer",
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        verbose_name="Amount",
                    ),
                ),
                ("iban", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In progress"),
                            ("ACCEPTED", "Accepted"),
                        ],
                        default="OPEN",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parking_permits.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "permit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund",
                        to="parking_permits.parkingpermit",
                        verbose_name="Permit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
            },
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="parking_zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="parking_permits.parkingzone",
                verbose_name="Parking zone",
            ),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="parking_permits.vehicle",
                verbose_name="Vehicle",
            ),
        ),
        migrations.CreateModel(
            name="DrivingLicence",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("valid_start", models.DateField(verbose_name="Valid start")),
                ("valid_end", models.DateField(verbose_name="Valid end")),
                ("active", models.BooleanField(default=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="driving_licence",
                        to="parking_permits.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "driving_classes",
                    models.ManyToManyField(to="parking_permits.DrivingClass"),
                ),
            ],
            options={
                "verbose_name": "Driving licence",
                "verbose_name_plural": "Driving licences",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="parking_permits.parkingzone",
                verbose_name="Zone",
            ),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Company name")),
                (
                    "business_id",
                    models.CharField(max_length=32, verbose_name="Business Id"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parking_permits.address",
                        verbose_name="Address",
                    ),
                ),
                (
                    "company_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parking_permits.customer",
                        verbose_name="Company owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AddField(
            model_name="address",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parking_permits.parkingzone",
                verbose_name="Zone",
            ),
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Price"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("COMPANY", "Company"), ("RESIDENT", "Resident")],
                        default="RESIDENT",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="parking_permits.parkingzone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price",
                "verbose_name_plural": "Prices",
                "unique_together": {("zone", "type", "year")},
            },
        ),
    ]
