# Generated by Django 3.2 on 2021-12-10 09:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "talpa_order_id",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="Talpa order id",
                    ),
                ),
                (
                    "talpa_subscription_id",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="Talpa subscription id",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("ORDER", "Order"), ("SUBSCRIPTION", "Subscription")],
                        default="ORDER",
                        max_length=50,
                        verbose_name="Order type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=50,
                        verbose_name="Order status",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="parking_permits.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "talpa_product_id",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="Talpa product id",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("COMPANY", "Company"), ("RESIDENT", "Resident")],
                        default="RESIDENT",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Unit price"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly")],
                        default="MONTHLY",
                        max_length=50,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="VAT"
                    ),
                ),
                (
                    "low_emission_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Low emission discount",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="parking_permits.parkingzone",
                        verbose_name="zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "talpa_order_item_id",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="Talpa order item id",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Unit price"
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="VAT"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="parking_permits.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "permit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_item",
                        to="parking_permits.parkingpermit",
                        verbose_name="Parking permit",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parking_permits.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order item",
                "verbose_name_plural": "Order items",
            },
        ),
    ]
