# Generated by Django 3.2 on 2021-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0002_order_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingzone",
            name="name",
            field=models.CharField(max_length=128, unique=True, verbose_name="Name"),
        ),
    ]
