# Generated by Django 3.2 on 2021-12-15 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0003_alter_parkingzone_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="permit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_item",
                to="parking_permits.parkingpermit",
                verbose_name="Parking permit",
            ),
        ),
    ]
