# Generated by Django 3.2 on 2022-01-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0007_alter_product_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingpermit",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="parkingpermit",
            name="subscription_id",
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permits",
                to="parking_permits.order",
                verbose_name="Order",
            ),
        ),
    ]
