# Generated by Django 3.2 on 2022-01-21 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parking_permits", "0008_add_parkingpermit_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refund",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="permit",
        ),
        migrations.AddField(
            model_name="refund",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="refund",
            name="order",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund",
                to="parking_permits.order",
                verbose_name="Permit",
            ),
            preserve_default=False,
        ),
    ]
