# Generated by Django 3.2 on 2022-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0009_update_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
    ]
