# Generated by Django 3.2 on 2022-01-26 11:27

from django.db import migrations, models


def copy_unit_price_to_payment_unit_price(apps, schema_editor):
    OrderItem = apps.get_model("parking_permits", "OrderItem")
    OrderItem.objects.update(payment_unit_price=models.F("unit_price"))


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0011_alter_orderitem_permit"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="payment_unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="Payment unit price",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            copy_unit_price_to_payment_unit_price, migrations.RunPython.noop
        ),
    ]
