# Generated by Django 3.2 on 2022-02-10 09:59

from django.db import migrations, models


# The IDENTITY field requires Postgresql 10+
CREATE_ORDER_NUMBER_SQL = """
ALTER TABLE parking_permits_order
ADD COLUMN order_number INT GENERATED ALWAYS AS IDENTITY;
"""

DROP_ORDER_NUMBER_SQL = """
ALTER TABLE parking_permits_order
DROP COLUMN order_number;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0014_alter_parkingpermit_customer"),
    ]

    operations = [
        migrations.RunSQL(
            CREATE_ORDER_NUMBER_SQL,
            DROP_ORDER_NUMBER_SQL,
        ),
    ]
