# Generated by Django 3.2 on 2022-02-10 14:17

from django.db import migrations, models


# The IDENTITY field requires Postgresql 10+
CREATE_REFUND_NUMBER_SQL = """
ALTER TABLE parking_permits_refund
ADD COLUMN refund_number INT GENERATED ALWAYS AS IDENTITY;
"""

DROP_REFUND_NUMBER_SQL = """
ALTER TABLE parking_permits_refund
DROP COLUMN refund_number;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0015_order_order_number"),
    ]

    operations = [
        migrations.RunSQL(
            CREATE_REFUND_NUMBER_SQL,
            DROP_REFUND_NUMBER_SQL,
        ),
    ]
