# Generated by Django 3.2 on 2022-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0016_refund_refund_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="iban",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
