# Generated by Django 3.2 on 2022-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0018_parkingpermit_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="holder",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="category",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="production_year",
        ),
        migrations.RemoveField(
            model_name="drivingclass",
            name="class_name",
        ),
        migrations.RemoveField(
            model_name="drivinglicence",
            name="valid_end",
        ),
        migrations.RemoveField(
            model_name="drivinglicence",
            name="valid_start",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="low_emission_vehicle",
        ),
    ]
