# Generated by Django 3.2 on 2022-03-14 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0019_parkingpermit_remove_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="weight",
            field=models.IntegerField(default=0, verbose_name="Total weigh of vehicle"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M1", "M1"),
                    ("M2", "M2"),
                    ("N1", "N1"),
                    ("N2", "N2"),
                    ("L3e-A1", "L3e-A1"),
                    ("L3e-A2", "L3e-A2"),
                    ("L3e-A3", "L3e-A3"),
                    ("L3e-A1E", "L3e-A1E"),
                    ("L3e-A2E", "L3e-A2E"),
                    ("L3e-A3E", "L3e-A3E"),
                    ("L3e-A1T", "L3e-A1T"),
                    ("L3e-A2T", "L3e-A2T"),
                    ("L3e-A3T", "L3e-A3T"),
                    ("L4e", "L4e"),
                    ("L5e-A", "L5e-A"),
                    ("L5e-B", "L5e-B"),
                    ("L6e-A", "L6e-A"),
                    ("L6e-B", "L6e-B"),
                    ("L6e-BP", "L6e-BP"),
                    ("L6e-BU", "L6e-BU"),
                ],
                max_length=16,
                verbose_name="VehicleClass",
            ),
        ),
        migrations.AddField(
            model_name="drivinglicence",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AddField(
            model_name="drivinglicence",
            name="start_date",
            field=models.DateField(verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="drivingclass",
            name="identifier",
            field=models.CharField(max_length=32, verbose_name="Identifier"),
        ),
        migrations.AlterField(
            model_name="lowemissioncriteria",
            name="power_type",
            field=models.CharField(
                choices=[
                    ("ELECTRIC", "Electric"),
                    ("BENSIN", "Bensin"),
                    ("DIESEL", "Diesel"),
                    ("BIFUEL", "Bifuel"),
                ],
                max_length=50,
                verbose_name="Power type",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="power_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ELECTRIC", "Electric"),
                    ("BENSIN", "Bensin"),
                    ("DIESEL", "Diesel"),
                    ("BIFUEL", "Bifuel"),
                ],
                max_length=50,
                verbose_name="Power type",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="emission_type",
            field=models.CharField(
                choices=[("NEDC", "NEDC"), ("WLTP", "WLTP")],
                default="WLTP",
                max_length=16,
                verbose_name="Emission type",
            ),
        ),
    ]
