# Generated by Django 3.2.12 on 2022-04-01 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0020_parkingpermit_add_or_alter_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="primary",
        ),
        migrations.RemoveField(
            model_name="address",
            name="source_id",
        ),
        migrations.RemoveField(
            model_name="address",
            name="source_system",
        ),
        migrations.RemoveField(
            model_name="address",
            name="zone",
        ),
        migrations.AddField(
            model_name="address",
            name="_zone",
            field=models.ForeignKey(
                blank=True,
                db_column="zone",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parking_permits.parkingzone",
                verbose_name="Zone",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AddField(
            model_name="address",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
    ]
