# Generated by Django 3.2.12 on 2022-04-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0021_update_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Paid time"),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permits",
                to="parking_permits.address",
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="type",
            field=models.CharField(
                choices=[("RESIDENT", "Resident"), ("COMPANY", "Company")],
                default="RESIDENT",
                max_length=32,
                verbose_name="Type",
            ),
        ),
    ]
