# Generated by Django 3.2 on 2021-06-17 06:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingzone",
            name="shared_product_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
