# Generated by Django 3.2 on 2021-06-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0004_use_enums_for_model_field_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingzone",
            name="shared_product_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
