# Generated by Django 3.2 on 2021-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0006_product_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lowemissioncriteria",
            name="emission_limit_nedc",
        ),
        migrations.RemoveField(
            model_name="lowemissioncriteria",
            name="emission_limit_wltp",
        ),
        migrations.AddField(
            model_name="lowemissioncriteria",
            name="euro_min_emission_limit",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Euro minimum emission limit"
            ),
        ),
        migrations.AddField(
            model_name="lowemissioncriteria",
            name="nedc_max_emission_limit",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="NEDC maximum emission limit"
            ),
        ),
        migrations.AddField(
            model_name="lowemissioncriteria",
            name="wltp_max_emission_limit",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="WLTP maximum emission limit"
            ),
        ),
    ]
