# Generated by Django 3.2 on 2021-08-13 08:55

from django.db import migrations, models
import django.db.models.deletion
import parking_permits_app.models.parking_permit


class Migration(migrations.Migration):

    dependencies = [
        (
            "parking_permits_app",
            "0013_alter_all_fields_which_used_constants_as_choices",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="consent_low_emission_accepted",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="consent_terms_of_use_accepted",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="parking_zone",
        ),
        migrations.AddField(
            model_name="address",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parking_permits_app.parkingzone",
                verbose_name="Zone",
            ),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="consent_low_emission_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="identifier",
            field=models.IntegerField(
                db_index=True,
                editable=False,
                unique=True,
            ),
        ),
    ]
