# Generated by Django 3.2 on 2021-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0019_address_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city_sv",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="City sv"
            ),
        ),
    ]
