# Generated by Django 3.2 on 2021-09-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0020_address_city_sv"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingzone",
            name="description_sv",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description sv"
            ),
        ),
    ]
