# Generated by Django 3.2 on 2021-09-13 06:31
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0021_parkingzone_description_sv"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpermit",
            name="month_count",
            field=models.IntegerField(default=0, verbose_name="Month count"),
        ),
        migrations.AlterField(
            model_name="parkingpermit",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("FIXED_PERIOD", "FIXED_PERIOD"),
                    ("OPEN_ENDED", "OPEN_ENDED"),
                ],
                default="OPEN_ENDED",
                max_length=16,
                verbose_name="Contract type",
            ),
        ),
        migrations.AlterField(
            model_name="parkingpermit",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("PAID", "PAID"),
                    ("CANCELLED", "CANCELLED"),
                    ("EXPIRED", "EXPIRED"),
                ],
                default="DRAFT",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="parkingpermit",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Start time"
            ),
        ),
        migrations.DeleteModel(
            name="ContractType",
        ),
    ]
