# Generated by Django 3.2 on 2021-09-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0022_move_contract_type_filed_to_permit_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpermit",
            name="start_type",
            field=models.CharField(
                choices=[("IMMEDIATELY", "IMMEDIATELY"), ("FROM", "FROM")],
                default="IMMEDIATELY",
                max_length=16,
                verbose_name="Start type",
            ),
        ),
        migrations.AlterField(
            model_name="parkingpermit",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("VALID", "VALID"),
                    ("CANCELLED", "CANCELLED"),
                    ("EXPIRED", "EXPIRED"),
                ],
                default="DRAFT",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
