# Generated by Django 3.2 on 2021-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0023_add_start_type_and_change_paid_to_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpermit",
            name="month_count",
            field=models.IntegerField(default=1, verbose_name="Month count"),
        ),
    ]
