# Generated by Django 3.2 on 2021-09-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0024_default_parkingpermit_month_count_to_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="primary",
            field=models.BooleanField(default=False, verbose_name="Primary address"),
        ),
    ]
