# Generated by Django 3.2 on 2021-10-29 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0027_order_id_and_subscription_id_to_permit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpermit",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Start time"
            ),
        ),
        migrations.AlterField(
            model_name="parkingpermit",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("PROCESSING", "PROCESSING"),
                    ("VALID", "VALID"),
                    ("CANCELLED", "CANCELLED"),
                    ("EXPIRED", "EXPIRED"),
                ],
                default="DRAFT",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
