# Generated by Django 3.2 on 2021-11-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0028_process_status_and_time_zone_as_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address_security_ban",
            field=models.BooleanField(
                default=False, verbose_name="Address security ban"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="driver_license_checked",
            field=models.BooleanField(
                default=False, verbose_name="Driver's license checked"
            ),
        ),
    ]
