# Generated by Django 3.2 on 2021-11-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0029_add_more_customer_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="low_emission_vehicle",
            field=models.BooleanField(
                default=False, verbose_name="Low emission vehicle"
            ),
        ),
    ]
