# Generated by Django 3.2 on 2021-11-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0031_create_refund_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpermit",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("ARRIVED", "ARRIVED"),
                    ("PROCESSING", "PROCESSING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                    ("PAYMENT_IN_PROGRESS", "PAYMENT_IN_PROGRESS"),
                    ("VALID", "VALID"),
                    ("CLOSED", "CLOSED"),
                ],
                default="DRAFT",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
