# Generated by Django 3.2 on 2021-11-18 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0032_alter_parkingpermit_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refund",
            name="request_date",
        ),
        migrations.AlterField(
            model_name="refund",
            name="permit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund",
                to="parking_permits_app.parkingpermit",
                verbose_name="Permit",
            ),
        ),
    ]
