# Generated by Django 3.2 on 2021-11-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0033_update_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="type",
            field=models.CharField(
                choices=[("resident", "Resident"), ("company", "Company")],
                default="resident",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="year",
            field=models.IntegerField(default=2021, verbose_name="Year"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="price",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prices",
                to="parking_permits_app.parkingzone",
                verbose_name="Zone",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="price",
            unique_together={("zone", "type", "year")},
        ),
        migrations.RemoveField(
            model_name="price",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="price",
            name="start_date",
        ),
    ]
