# Generated by Django 3.2 on 2021-11-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0034_update_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Serial number"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="emission",
            field=models.IntegerField(blank=True, null=True, verbose_name="Emission"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="emission_type",
            field=models.CharField(
                choices=[("EURO", "EURO"), ("NEDC", "NEDC"), ("WLTP", "WLTP")],
                default="EURO",
                max_length=16,
                verbose_name="Emission type",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="holder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles_holder",
                to="parking_permits_app.customer",
                verbose_name="Holder",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="last_inspection_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Last inspection date"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles_owner",
                to="parking_permits_app.customer",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="production_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Vehicle production_year"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="parking_permits_app.vehicletype",
                verbose_name="Vehicle type",
            ),
        ),
    ]
