# Generated by Django 3.2 on 2021-11-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0035_update_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=32, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="national_id_number",
            field=models.CharField(
                max_length=16,
                unique=True,
                blank=True,
                verbose_name="National identification number",
            ),
        ),
    ]
