# Generated by Django 3.2 on 2021-12-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0036_update_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="parking_permits_app.parkingzone",
                verbose_name="Zone",
            ),
        ),
    ]
