# Generated by Django 3.2 on 2021-12-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0037_customer_zone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingpermit",
            name="consent_low_emission_accepted",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="consent_low_emission_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
