# Generated by Django 3.2 on 2021-12-02 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0038_move_consent_low_emission_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city_sv",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="City sv"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True, default="", max_length=5, verbose_name="Postal code"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="street_name_sv",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Street name sv"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="source_id",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Source id"
            ),
        ),
    ]
