# Generated by Django 3.2 on 2021-12-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits_app", "0039_update_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingzone",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parkingzone",
            name="description_sv",
            field=models.TextField(
                blank=True, default="", verbose_name="Description sv"
            ),
            preserve_default=False,
        ),
    ]
